### ISSUE TITLE
Error triggering gradle build

### ISSUE THREAD

**Issue by rpattabi** [cesarferreira/dryrun#18] opened 2016-02-29 01:08 UTC
I get this error:

```
 [~] $ dryrun https://github.com/cesarferreira/android-helloworld
Cloning into '/tmp/dryrun/cesarferreira/android-helloworld'...
remote: Counting objects: 136, done.
remote: Total 136 (delta 0), reused 0 (delta 0), pack-reused 136
Receiving objects: 100% (136/136), 2.24 MiB | 1.08 MiB/s, done.
Resolving deltas: 100% (44/44), done.
Checking connectivity... done.
gradlew: 158: gradlew: Syntax error: "(" unexpected
Failed
Installing github.cesarferreira.helloworld...
executing: adb shell am start -n "github.cesarferreira.helloworld/github.cesarferreira.helloworld.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER

Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=github.cesarferreira.helloworld/.MainActivity }
Error type 3
Error: Activity class {github.cesarferreira.helloworld/github.cesarferreira.helloworld.MainActivity} does not exist.

> If you want to remove the app you just installed, execute:
adb uninstall github.cesarferreira.helloworld
```

May be due to gradle version differences?

**Comment by cesarferreira** [comment] 2016-02-29 09:36
Hey,
thanks for reporting, this is a duplicate of the #3 let's keep the conversation there

**Closed as completed by cesarferreira** 2016-02-29 09:36 UTC
Labels: duplicate
