### ISSUE TITLE
File path too long on Windows

### ISSUE THREAD

**Issue by tazesk** [cesarferreira/dryrun#61] opened 2016-11-10 08:00 UTC
Hi,i have some problem for "File path too long on Windows, keep below 240 characters".
    can i change the porject path? or any the better way can fix it? thank you.
 
C:\Users\Administrator\AppData\Local\Temp\dryrun\7f9e37d7552261f45a2a5d650a2af78
6a55622ac935840acf6ec163d1304794e\lib\build\intermediates\exploded-aar\com.andro
id.support\appcompat-v7\24.2.0\res\drawable-hdpi-v4\abc_ic_menu_share_mtrl_alpha
.png: Error: File path too long on Windows, keep below 240 characters

**Comment by cesarferreira** [comment] 2016-11-10 21:43
This is a duplicate of #55

**Comment by cesarferreira** [comment] 2016-11-11 00:14
I'm fixing this on #55 Please follow that issue instead

**Closed as completed by cesarferreira** 2016-11-11 00:14 UTC
Labels: duplicate
